### ISSUE TITLE
Anotar.Serilog does not work in the main assembly

### ISSUE THREAD

**Issue by yanglee** [Fody/Anotar#10]
Hello,

Here is an example project that can reproduce the issue:
https://dl.dropboxusercontent.com/u/46508238/github.com/TestAnotar-2013-05-13.zip

Steps to reproduce the issue:

1) Create a Console project, and a Portable Class Library, Console references PCL;
2) Add the following NuGet packages to both projects:

```
- Anotar.Serilog.Fody.1.6.0.0
- Fody.1.13.8.0
- Serilog.0.2.9
```

3) Add the following code to Console project:

```
internal class Program
{
    static void Main(string[] args)
    {
        var log = new Serilog.LoggerConfiguration()
            .WriteTo.ColoredConsole()
            .CreateLogger();
        Serilog.Log.Logger = log;

        Serilog.Log.Information("Main assembly: Hello from Serilog");
        Anotar.Serilog.Log.Information("Main assembly: Hello from Anotar");

        new ClassFromAnotherAssembly().Hello();
    }
}
```

4) Add the following code to PCL:

```
public class ClassFromAnotherAssembly
{
    public void Hello()
    {
        Serilog.Log.Information("Another assembly: Hello from Serilog");
        Anotar.Serilog.Log.Information("Another assembly: Hello from Anotar");
    }
}
```

5) Ctrl+F5

6) Got the following output:

```
05/13/2013 20:17:33 [Information] Main assembly: Hello from Serilog
05/13/2013 20:17:33 [Information] Another assembly: Hello from Serilog
05/13/2013 20:17:33 [Information] Another assembly: Hello from Anotar
```

So it seems Anotar.Serilog does not work in the main assembly (I've also tested this in a WPF app, same result).

**Comment by arteny** [comment]
But is it possible to fix to make Anotar logging working from non static constuctor? For example when it is intiialized from MainWindow constructor (WPF), original Serilog logging works well, Anotar logging doesn't work at all.
