### ISSUE TITLE
ModuleWeaver.LoadSystemTypes throw NRE on .NET Standard projects

### ISSUE THREAD

**Issue by mstyura** [Fody/Anotar#103]
Implementation of `LoadSystemTypes` does not take into account types layout between assemblies of .NET Standard libraries (absence of `mscorlib.dll`) resulting in inability to build due to internal exception in this plugin.

**Comment by tpluscode** [comment]
Interesting. In what circumstances does that occur? Why didn't tests catch the issues you fix in your PR?

**Comment by mstyura** [comment]
@tpluscode it happens always when Fody.Anotar is added to any .NET Standard 1.4 class library.

**Comment by mstyura** [comment]
@tpluscode looks like there are several differences between test and actual project:
1. `CustomAssemblyToProcess` project, which seems to be an assembly to be weaved in test, does not use Anotar.Custom.Fody package and does not have `FodyWeavers.xml` file, which defines which weaver should be execution.
2. `CustomTests` which looks like actual tests suite executed to verify weaving. It perform custom weaving in process. So when `CustomAssemblyToProcess` is compiled it doesn't have any changes applied by weaver. When tests from `CustomTests` is executed they modify original unmodified `CustomAssemblyToProcess` in runtime and then verify the results of weaving.

When `CustomAssemblyToProcess` is updated to use Nuget package of `Anotar.Custom.Fody` and `FodyWeavers.xml` is added, the compilation of `Anotar.Custom.Fody` become broken with `NRE`.

**Comment by tpluscode** [comment]
Fixed by #104

**Comment by tpluscode** [comment]
Thank you very much for finding and fixing this @mstyura. I've just published 3.3.1-beta0002 on NuGet
