### ISSUE TITLE
Anotar.Catel.Fody not compatible with Catel 5

### ISSUE THREAD

**Issue by Keops31** [Fody/Anotar#108]
Error message at compilation:
"Error: Fody: Expected to find method 'WriteWithData(Exception, String, Object, LogEvent)' on type 'Catel.Logging.ILog'."

See below URL where this issue was initially raised to Catel but identified as Anotar.Catel.Fody issue.
https://github.com/Catel/Catel/issues/1069

**Comment by tpluscode** [comment]
Hi @Keops31. Indeed looks like the API of Catel changed. I'll try to roll out an updated package as soon as possible.
