### ISSUE TITLE
Anotar custom crashed when used in .NET Standard 2.0 library

### ISSUE THREAD

**Issue by mstyura** [Fody/Anotar#110]
`.NET Standard 2.0` introduces the notion of netstandard.dll which contains some of types required by weaver. Current implementation of `LoadSystemTypes` is not aware of such changes and crashes in on e of `First` linq methods.

**Comment by tpluscode** [comment]
Hi. Has the beta package worked?

**Comment by mstyura** [comment]
Yes, with published beta package Anotar works on .NET Standard 2.0 project.
