### ISSUE TITLE
Log exceptions from async methods

### ISSUE THREAD

**Issue by AsValeO** [Fody/Anotar#112]
Anotar is cool, but unfortunately it is useless for exception logging in modern apps because of this feature missing.
UPD: Is **AsyncErrorHandler** the thing I am looking for?
UPD2: It works!
Thank you, great libs!

**Comment by jparaya** [comment]
How did you solve this issue? Anotar+AsyncErrorHandler works fine, but I lose the details of the method call and line nr. It always track the error as coming from the HandleException method
