### ISSUE TITLE
Missing element <Anotar.Serilog/> in FodyWeavers.xml

### ISSUE THREAD

**Issue by altmann** [Fody/Anotar#113]
Hi, 

if I install Anotar.Serilog.Fody via Nuget then the file FodyWeavers.xml is added to the solution. The problem is that this file doesn't contain the element <Anotar.Serilog/>. I have to manually add it.

**Comment by tpluscode** [comment]
Are you using the new csproj format and dotnet tooling?

**Comment by altmann** [comment]
I use VS2017 (15.4.3) and the Console application target .NET 4.6.1. So no old csproj format.

**Comment by SimonCropp** [comment]
unfortunately this is going to be the new norm moving forward. you will need to manually add or remove the weaver node when u install or uninstall the nuget. The nuget team have removed this feature in the new project system and, as yet, there is no replacement. given the majority of projects will over time convert, i made the decision that, for the sake of consistency and ease of writing doco, to change it to a manual action for all project systems.

I have added this guidance to fody https://github.com/Fody/Fody/#usage and am gradually converting weavers over to the new approach

sorry for any inconvenience

**Comment by altmann** [comment]
Ah okay, no problem if we have to add it manually then it is okay. It would be cool if you add this step in the docu at https://github.com/Fody/Anotar so that this important information is not hidden from Anotar users.

Thanks for your help - issue is closed now.

**Comment by SimonCropp** [comment]
done https://github.com/Fody/Anotar/commit/8540d3f637e0e1f42986b5141eb2b88ee328587f
