### ISSUE TITLE
No logging with Anotar.Serilog.Fody

### ISSUE THREAD

**Issue by altmann** [Fody/Anotar#114]
Hi, 

I install Anotar.Serilog.Fody via Nuget and add the missing element <Anotar.Serilog/> in FodyWeavers.xml. (see #113)

I add the following lines to configure Serilog and make some log statements. 

    class Program
    {
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Console()
                .CreateLogger();

            var logger = Log.ForContext<Program>();

            logger.Information("direct log message");

            LogTo.Information("fody log message");
            LogTo.Error("second log");

            //Log.Information("hello");

            System.Console.ReadKey();
        }
    }

Only "direct log message" is displayed in Console. "fody log message" and "second log" are not logged. Whats wrong?

**Comment by tpluscode** [comment]
Indeed but I'm completely surprised by what is happening here.

@SimonCropp it's very weird, because the transformed code looks fine. If I copy and paste the reverse emitted output to code it works of course. Yet there is no output. Have you seen something like that before?

**Comment by SimonCropp** [comment]
so this effectively results in 

```
public class SerilogExplicitSample
{
    static ILogger AnotarLogger = Log.ForContext<SerilogExplicitSample>();

    static void Main()
    {
        Log.Logger = new LoggerConfiguration().MinimumLevel.Information().CreateLogger();
        var logger = Log.ForContext<SerilogExplicitSample>();
        logger.Information("direct log message");
        AnotarLogger.ForContext("MethodName", "Void Main()")
            .ForContext("LineNumber", 19)
            .Information("fody log message");
        AnotarLogger.ForContext("MethodName", "Void Main()")
            .ForContext("LineNumber", 20)
            .Error("second log");
        Console.ReadKey();
    }
}
```

note that the `SerilogExplicitSample.AnotarLogger` field is assigned prior to `Log.Logger` be in set in the main. this means it is using the default no-op logger of serilog.

So u effectively have a race condition

do the log setup in the static constructor instead

```
public class SerilogExplicitSample
{
    static SerilogExplicitSample()
    {
        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Information()
            .CreateLogger();
    }
```

**Comment by altmann** [comment]
Okay, this makes sense. It works now. Thanks for your help.
