### ISSUE TITLE
Nuget restore warning in .NET Standard 2.0 class library project with Anotar.Log4Net.Fody

### ISSUE THREAD

**Issue by altmann** [Fody/Anotar#115]
Hi,

If I install Anotar.Log4Net 3.3.2-beta1 or 3.3.1 via Nuget then I get a warning from visual studio (within the new area Dependencies -> Nuget in the solution explorer):

"Package ... was restored using ".NETFramework,Version=v4.6.1" instead of the project target framework ".NETStandard,Version=v2.0". This package may not be fully compatible with your project". 

I get no build error but log messages are not logged. Whats wrong in this case?

**Comment by tpluscode** [comment]
Log4Net hasn't been migrated to net standard yet. Please see #98. 

If you need it, I can work on it over the weekend

**Comment by altmann** [comment]
We make currently a spike if we use Anotar.Fody in our project or not. So it is not very urgent. Now we know thats theoretically possible to make it work on .NET Standard, which is a MUST HAVE feature for us. Thanks for your fast response.
