### ISSUE TITLE
Fix Linux Nuget Referance (Case Sensitive)

### ISSUE THREAD

**Issue by NPSF3000** [Fody/Anotar#121]
Fody now runs on linux - Yay!

Anotar nuget packages are named like this:
_/root/.nuget/packages/anotar.serilog.fody/4.0.1/netstandardweaver/**Anotar.Serilog.Fody.dll**_ 

While Fody is looking for packages named like this:
_/root/.nuget/packages/anotar.serilog.fody/4.0.1/netstandardweaver/**anotar.serilog.fody.dll**_

Small naming difference, but an important one when dealing with case sensitive filesystems.

**Comment by SimonCropp** [comment]
isnt this a bug in nuget that it restores the files with the wrong case?

**Comment by SimonCropp** [comment]
can u try fody 2.3.22

**Comment by NPSF3000** [comment]
@SimonCropp I'll give it a try this week.  Thanks.
