### ISSUE TITLE
Make Anotar.Serilog compatible with SerilogAnalyzer

### ISSUE THREAD

**Issue by j2jensen** [Fody/Anotar#123]
SerilogAnalyzer is a Roslyn analyzer that gives useful compile-time errors when logging code is not formed correctly. I created [this issue](https://github.com/Suchiman/SerilogAnalyzer/issues/30) over at the SerilogAnalyzer repo, hoping that they could pick up the Anotar.Serilog methods, and it looks like if you add `Serilog.Core.MessageTemplateFormatMethodAttribute` to the methods in [LogTo](https://github.com/Fody/Anotar/blob/master/Serilog/Anotar.Serilog/LogTo.cs), SerilogAnalyzer should automatically be able to pick that up.

If this works, I won't have to choose between having the analyzer's help and having the extra information and concise code that Anotar provides.

**Comment by SimonCropp** [comment]
sounds cool. i will accept a PR for this :)

**Comment by j2jensen** [comment]
Pull Request submitted. I verified that if I reference the resulting DLL locally, SerilogAnalyzer picks up on these methods and generates compile-time errors for malformed templates.

**Comment by SimonCropp** [comment]
sorry. forgot to close the loop on this. it is now deployed. thanks for the PR

**Comment by j2jensen** [comment]
Awesome. This totally made my week!
