### ISSUE TITLE
Versions 4.x+ only for .NET 4.5.2 and netstandard?

### ISSUE THREAD

**Issue by mennodeij** [Fody/Anotar#125]
My projects target the 4.5.1 .NET runtime and fail to install the 4.x NuGet packages. Anotar.Fody version 3.3.1 nuget package installs fine.

Can the configuration/dependencies of 4.x be tuned such that *it just works* in 4.x like it does in 3.x?

**Comment by SimonCropp** [comment]
452 has been out for almost 4 years. Is it not possible for you to update?

**Comment by SimonCropp** [comment]
also note that 451 is no longer supported https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview
