### ISSUE TITLE
"kills" ModuleInit

### ISSUE THREAD

**Issue by sapatag** [Fody/Anotar#129]
Created WPF app with Catel 5.3.0.
Added Fody 3.0.3 ModuleInit.Fody 1.8.0; ModuleInit is working OK.
Added Anotar.Catel.Fody 4.3.2 (with Fody.Packaging 3.0.1 or 3.0.3) and ModuleInit stops calling ModuleInitializer.Initialize()
After removing Anotar it works ok again.

**Comment by SimonCropp** [comment]
Happy to take a pull request that fixes this

**Comment by sapatag** [comment]
I'm afraid it's beyond me:(
