### ISSUE TITLE
Anotar.NLog.Fody not working from version 4.0.0 with WPF projects

### ISSUE THREAD

**Issue by codingseb** [Fody/Anotar#130]
I created a simple WPF Project to test Anotar.NLog.Fody. From version 4.0.0 to 4.3.2, none are working.
if I install the 3.3.1 version it's working. Am I doing Something wrong with newer versions ?
It seems that the replacement code is never injected by fody. It generate a System.NotImplementedException on LogTo.Error("Test").

The code of the project to reproduce the problem :
[https://github.com/codingseb/LogTest](https://github.com/codingseb/LogTest)

**Comment by SimonCropp** [comment]
u got bit by the "nuget installed the oldest and most buggy version of any dependency" bug. 

fixed it here for u https://github.com/codingseb/LogTest/pull/1
