### ISSUE TITLE
[LogToErrorOnException] with catch

### ISSUE THREAD

**Issue by arteny** [Fody/Anotar#259]
Could you please add such a feature with the new attribute like [CatchAndLogToErrorOnException] or add a parameter to the existing attribute?
Related link: https://stackoverflow.com/questions/57788029/anotar-serilog-logtoerroronexception-add-catch/57814348#57814348

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
