### ISSUE TITLE
LogTo class all  throw new NotImplementedException();

### ISSUE THREAD

**Issue by JERRYZFC** [Fody/Anotar#269]
Hello friend ,why the logto class leaves all function a throw new NotImplementedException();
then i have no idea how to use it in my own project ,could you mind giving me some idea please?
thanks!

**Comment by tpluscode** [comment]
The `LogTo` methods do indeed throw an exception. They should be replaced at runtime with the actual login framework of choice. Please share a minimal project which reproduces the problem

**Comment by JERRYZFC** [comment]
thanks tpluscode 
i use it with log4net and it works well now ,thanks ,my own not familiar with this great framework ,
