### ISSUE TITLE
It is not thread-safety

### ISSUE THREAD

**Issue by arteny** [Fody/Anotar#337]
Following code shows only 2nd and 3rd message, but not shows a message from Anotar

			Observable.Interval(TimeSpan.FromMinutes(1)).Subscribe(_ =>
				{
					LogTo.Information($"Missed packages: {_missed}");
					Log.Information($"Missed packages: {_missed}");
					Console.WriteLine($"Missed packages: {_missed}");
					_missed = 0;
				}
			);

library System.Observable is used here

**Comment by SimonCropp** [comment]
can you submit a failing test as a PR

**Comment by arteny** [comment]
I don't know what is PR. The failing test is above. only add before:
int _missed = 0;
also note, that if call LogTo from main thread (for example right after Observable.Interval), it works well.

**Comment by SimonCropp** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by tom-englert** [comment]
@arteny since Anotar calls just get translated into calls to the logging framework, the problem could be the loggeing framework - so which are you using?
