### ISSUE TITLE
Conditional logging

### ISSUE THREAD

**Issue by tpluscode** [Fody/Anotar#52]
Hi. I see that readme lists `IsXxEnabled` properties in logger members. However I see that no checks are actually injected around logging calls. Is there a switch to enable them?

**Comment by SimonCropp** [comment]
the is enable is only used in exception handling. are you saying that is not happening?

**Comment by tpluscode** [comment]
Don't know. I was thinking though that it could also wrap the standard `LogTo.XYZ()` call. Why doesn't it?

**Comment by SimonCropp** [comment]
because those IsXxEnabled methods are exposed from logging libs to allow developers to avoid the expense of building up the thing (usually a string) to pass in to the log method. in the context of IL I have no way of know where to start the if statement to avoid that expense.

**Comment by tpluscode** [comment]
I see, it makes sense.

And what about the lambda parameter overload that some libraries offer so that the expensive message buildup can be avoided. Have you considered supporting that for Loggers?

**Comment by SimonCropp** [comment]
sure that could be supported. which framework would u like to begin with?

**Comment by tpluscode** [comment]
I'd say NLog

**Comment by ziez** [comment]
Hi there. Actually sometimes such conditional logging can radically improve performance. 

In our project we use ```Anotar.Custom``` (based on EntLib LAB). We have a lot of Debug-level logging with a bunch of data: states, simple and complex method parameters, etc. Now we manually wrap hundreds of ```LogTo.Debug``` or ```LogTo.Information``` calls with conditions check. It does not look good. With ```Anotar``` we want to have a full abstraction from underlying logging library, but we get just half of it. 

Now we do so:
```csharp
if (LogToIf.Information) // LogToIf is our own class
{
    LogTo.Information("Method call: SetTaskResults({0}, [{1}], [{2}], [{3}])", 
        database, string.Join(", ", lockIds), string.Join(", ", tranIds), string.Join<TaskResult>(", ", results));
}
```
Arrays can be huge, but we want to log them if proper log level is configured. 

As you can see the preparation of the log message in our case can be too expensive, if we then just throw the message away. As @tpluscode I also was expected that all ```LogTo.MessageLevel``` calls wrapped in conditional checks automatically and I actually prefer having cheap ```IsDebugEnabled``` calls always rather then not having them at all.

As you guys already noted having lambda parameter overload can be a good solution. Another possible solution having methods like ```LogTo.IfDebug```, which will perform corresponding checks before building message, and I think this second approach is more elegant. What do you think?

**Comment by SimonCropp** [comment]
@ziez do you want to have a go at doing this in a Pull Request?

**Comment by ziez** [comment]
@SimonCropp yes, why not, I just wanted to discuss possible design decisions before start implementing it.

**Comment by SimonCropp** [comment]
@ziez happy to expose LogTo.IfDebug methods. it would actually be trivial to redirect those to the static logger. do you want to raise a different issue for that one

Although as discussed above it is difficult, at the IL level, to work out where to inject LogTo.IfDebug. So i think the delegate overrides would still be helpful.

**Comment by SimonCropp** [comment]
i should be clear. in some cases it may be possible to work out what code to wrap in a LogTo.IfDebug but it would push too much knowledge onto the user regarding the underlying IL generated.

**Comment by SimonCropp** [comment]
Ok I added isenabled checks https://github.com/Fody/Anotar#checking-logging-level

**Comment by SimonCropp** [comment]
https://github.com/Fody/Anotar#delegate-logging
