### ISSUE TITLE
Anotar.CommonLogging cannot wieve after update to Common Logging 3.0

### ISSUE THREAD

**Issue by crakinshot** [Fody/Anotar#55]
Installing Anotar.CommonLogging to a WPF class library. It installs a nuget dependency to Common.Logging.Core.  Yet, the wiever complaints it cannot find Common.Logging or Common.Logging.Portable. 

Exception:
Expected to find a reference to one of Common.Logging, Common.Logging.Portable.

**Comment by crakinshot** [comment]
Technically not a bug I guess. Although, I thought the whole reason for Common.Logging.Core was to abstract the implementation, thus Fody and Anotar should just need to call the Common.Logging.Core interface?

**Comment by crakinshot** [comment]
That said; I added a reference to Common.Logging as well and its still complaining (same exception).

**Comment by SimonCropp** [comment]
can u upload a repo somewhere?

**Comment by SimonCropp** [comment]
feel free to open a new issue when you upload a repro

**Comment by SimonCropp** [comment]
should be fixed in 2.16.2

**Comment by crakinshot** [comment]
Sorry, I should have closed this myself. I think version 3.0 broke a few things re: PCL, so I ported to Serilog.
