### ISSUE TITLE
Compilation error with Anotar.Log4Net.Fody 2.17.0 when LogTo method is passed a concatenated string

### ISSUE THREAD

**Issue by gsbastian** [Fody/Anotar#57]
Just upgraded to Anotar.Log4net.Fody 2.17.0, and immediately had a compilation error in one of our VB.NET projects in VS.NET 2013.  Targeting .NET 4.0.
```
The error info from Diagnostic MSBuild output:
        Executing Weaver  (TaskId:24)
MSBUILD : error : Fody: 'typeof' usages or passing `dynamic' params to 'LogTo' are not supported.
 'Links.Data.AccessObject Links.Data.AccessProcessor::ValidatePerson(System.String,System.Int32,System.DateTime,System.Boolean)'.
      Finished Fody 108ms. (TaskId:24)
Done executing task "Fody.WeavingTask" -- FAILED. (TaskId:24)
```
The offending line of code is:
```
LogTo.Debug("AX_SelectPeopleDataForAccess " & lPeopleId.ToString() & "," & AccessPointId.ToString() & "," & IIf(bAddFutureFamilyAccounts, "1", "0") & ",null")
```
Appears to dislike the concatenated string being passed in.

Changing the offending line to the following resolves this.
```
LogTo.Debug("AX_SelectPeopleDataForAccess {0},{1},{2},null" , lPeopleId , AccessPointId , IIf(bAddFutureFamilyAccounts, 1, 0))
```

**Comment by SimonCropp** [comment]
@gsbastian can you upload a repro somewhere?

**Comment by gsbastian** [comment]
@SimonCropp - I can identify the issue - its the IIf() statement, which returns object which is causing the issue.  

Here's a [repro](https://www.dropbox.com/s/jttb10y301s4tfw/ConcatenatedLogMessageRepro.zip?dl=0)

Note: The workaround is to add the ToString() to the IIF, however this used to work before upgrading to 2.17.0 of Anotar.Log4Net.Fody.

**Comment by SimonCropp** [comment]
unfortunately that works on my machine

**Comment by SimonCropp** [comment]
sorry. can repro now. only happens in release mode.
will have a go at fixing over the weekend

**Comment by SimonCropp** [comment]
WOW VB produces some dodgy IL

**Comment by SimonCropp** [comment]
So VB is effectively invoking that member using reflection

So this

    Sub Main()
        Dim message = IIf(True, "1", "0")
        LogTo.Debug(message)
    End Sub

Compiles to this 
```
Public Shared Sub Main()
	NewLateBinding.LateCall(Nothing, GetType(LogTo), "Debug", New Object()() { RuntimeHelpers.GetObjectValue(Interaction.IIf(True, "1", "0")) }, Nothing, Nothing, Nothing, True)
End Sub
```

And whats worse it does this in release mode.

**Comment by SimonCropp** [comment]
ok looking into this a bit more it seems VB doesnt know what to do with your code and is attempting to treat i with dynamic

And then Anotar throws since it cant reverse engineer the IL produced to do a dynamic envoke

Turning on strict option in the compiler results in 

```
Error	1	Option Strict On prohibits operands of type Object for operator '&'.	C:\Downloads\ConcatenatedLogMessageRepro\ConcatenatedLogMessageRepro\ConcatenatedLogMessageRepro\Module1.vb	7	77	ConcatenatedLogMessageRepro
```

if you click on the offending code `IIf(True, "1", "0")`. you will get prompted to do a direct cast which results in

```
LogTo.Debug("Test message" & int1.ToString() & " another message" & DirectCast(IIf(True, "1", "0"), String) & " more messages")
```

Which will produce the correct IL with no refelction

So I think the outcome here is you should compile VB in strict mode.
