### ISSUE TITLE
AsyncChecker is broken under Roslyn

### ISSUE THREAD

**Issue by distantcam** [Fody/Anotar#59]
Of course it is. 

Of course it is!

Anotar works fine with async methods under Roslyn. The only problem was the log type was the internal state machine and not the type I thought it would be.

**Comment by SimonCropp** [comment]
can u add a little more context

**Comment by distantcam** [comment]
How about a breaking test instead? https://github.com/distantcam/Anotar/tree/AsyncDelegate

Turns out it's when you have an async delegate, like so.

    public void AsyncDelegateMethod()
    {
        var action = new Action(async () => LogTo.Debug());
        action();
    }
