### ISSUE TITLE
Doesnt work on UWP because the assembly is not referenced by nuget

### ISSUE THREAD

**Issue by haefele** [Fody/Anotar#62]
I'm trying to get this working on UWP but it seems like I'm not getting the reference to the assembly, I don't have access to the LogTo class and thus can't use this weaver.

I think it might be because in the nuget package the Anotar.XYZ.dll assembly is directly in the lib folder.

**Comment by SimonCropp** [comment]
what nuget r u trying to use?

**Comment by haefele** [comment]
I'm trying to use the package Anotar.Custom.Fody

If you want I can create a step by step instruction of what I'm doing.

**Comment by SimonCropp** [comment]
2.19.2 is on nuget. can u try it

**Comment by haefele** [comment]
Yes, that works now!
Thank you very much for your help :smile:
