### ISSUE TITLE
Feature Request: Add support for "verbose" methods in logging frameworks

### ISSUE THREAD

**Issue by ravensorb** [Fody/Anotar#63]
It would be useful if "verbose" was also supported

**Comment by SimonCropp** [comment]
Which frameworks would u like verbose added to?

**Comment by ravensorb** [comment]
Personally I am a big fan of Serilog.  That said, I believe several of the major logging frameworks have a verbose concept.  Might be nice to add a verbose to all of them and then map it to debug for the few frameworks that do not support Verbose.

What do you think?

**Comment by SimonCropp** [comment]
Seems serilog is the only one that supports verbose. so i added that.

should not be on nuget
