### ISSUE TITLE
Feature Request: Add support for including namespace and class names

### ISSUE THREAD

**Issue by ravensorb** [Fody/Anotar#64]
It would be great if Anotar could be extended to support logging the full namespace and class name.  Either as additional context variables or as part of the method name

**Comment by SimonCropp** [comment]
The class and namespace a exposed through the instance of the logger. Why would u write them on every log message?

**Comment by ravensorb** [comment]
The example I have is a highly async application.  Consider multiple concurrent executions of the same methods or of methods with same name in different namespaces (like concrete implementations of interface contracts).   Without the full classname/namespace it is extremely difficult to match log lines with where in the code a possible issue occurred.

A very simple example might be -- consider a logging statement inside of a PropertyChanged notification method.  How could you ever determine which class triggered that? :smile:

**Comment by SimonCropp** [comment]
the static field that contains the logger has access to the type and namespace. you should be able to have that outputted correctly. if not upload a repro somewhere and i will have a look at it

**Comment by SimonCropp** [comment]
Does this help? https://github.com/serilog/serilog/issues/527

**Comment by ravensorb** [comment]
Partially.   I found that if I add "SourceContext" to my outputtemplate I am getting closer to what I would expect.  Now the only issue is I need to do a lot of custom "wrapping" so that I can combine with with the concept of a correlation id.  It seems like that since the Fody extension creates a custom static property only for calls to LogTo.  and not of all variables of type Serilog.Logger a lot of my code isn't getting the benefit of the extension.

Question -- any way to use the "LogTo." static property and pass in a context concept (like a begin context/end context idea)?

**Comment by SimonCropp** [comment]
> Now the only issue is I need to do a lot of custom "wrapping" so that I can combine with with the concept of a correlation id. It seems like that since the Fody extension creates a custom static property only for calls to LogTo. and not of all variables of type Serilog.Logger a lot of my code isn't getting the benefit of the extension.

If you have a static field in the class that will be picked up and used

https://github.com/Fody/Anotar/blob/master/SplatAssemblyToProcess/ClassWithExistingField.cs

Does that meet your requirement? 

> any way to use the "LogTo." static property and pass in a context concept (like a begin context/end context idea)

no there is not

**Comment by SimonCropp** [comment]
i think the original issue has been resolved here. so closing this
