### ISSUE TITLE
Anotar.CommonLogging.Fody throws exception upon build

### ISSUE THREAD

**Issue by dittodhole** [Fody/Anotar#65]
> 1>MSBUILD : error : Fody: An unhandled exception occurred:
> 1>MSBUILD : error : Exception:
> 1>MSBUILD : error : Expected to find a reference to one of Common.Logging,Common.Logging.Portable.
> 1>MSBUILD : error : StackTrace:
> 1>MSBUILD : error :    at ModuleWeaver.GetReference(String[] referenceNames) in C:\projects\anotar\CommonLoggingFody\ReferenceFinder.cs:line 38
> 1>MSBUILD : error :    at ModuleWeaver.FindReference() in C:\projects\anotar\CommonLoggingFody\ReferenceFinder.cs:line 12
> 1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\anotar\CommonLoggingFody\ModuleWeaver.cs:line 30
> 1>MSBUILD : error :    at lambda_method(Closure , Object )
> 1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 164
> 1>MSBUILD : error :    at InnerWeaver.Execute() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 82
> 1>MSBUILD : error : Source:
> 1>MSBUILD : error : Anotar.CommonLogging.Fody
> 1>MSBUILD : error : TargetSite:
> 1>MSBUILD : error : Mono.Cecil.AssemblyDefinition GetReference(System.String[])
> 1>MSBUILD : error : 
> 1>    Fody:   Finished Fody 30ms.

Anotar.CommonLogging.Fody: 2.19.2
Common.Logging.Core: 3.2.0
Framework: .NET 4.6

After adding Common.Logging.Portable, build succeeds. I suggest an update in the dependencies of the .nupkg file.

**Comment by SimonCropp** [comment]
sounds good. Send me a PR

**Comment by SimonCropp** [comment]
let me know if u get around to finishing a new PR for this https://github.com/Fody/Anotar/pull/66#discussion_r48254832

**Comment by dittodhole** [comment]
sorry, completely forgot about this PR - made a new one, please see https://github.com/Fody/Anotar/pull/72
