### ISSUE TITLE
Bug: Current implementation not Thread/Task safe

### ISSUE THREAD

**Issue by ravensorb** [Fody/Anotar#67]
I have been using the Anota Fody weaver for a week or so now and I am fairly confidant that it is not thread/task safe.  It appears that the static variable that is created works very well for a single threaded application, however as soon as you switch to an async model, you noticed that the Method in the log file does not match the actual logging entry -- this is due to the fact that the method is identified on the first thread and all other threads use it.

Please consider switching from a static to a local instance.

**Comment by SimonCropp** [comment]
Please upload a repro

**Comment by SimonCropp** [comment]
BTW I assume u r referring to serilog?

**Comment by ravensorb** [comment]
You are correct -- I am. I'll try to get a repro (or close this) sometime today.

**Comment by SimonCropp** [comment]
any luck on that repro?
