### ISSUE TITLE
It doesn't work for Serilog

### ISSUE THREAD

**Issue by arteny** [Fody/Anotar#68]
When using 
			LogTo.Debug("Before WaitStart");
it is logging as
2016-01-12 16:09:49.321 +03:00 [Debug] Before WaitStart
without class name, method name and line number.
What is wrong?

**Comment by SimonCropp** [comment]
try this 
```

        var configuration = new LoggerConfiguration()
            .MinimumLevel.Verbose();
        configuration.WriteTo.RollingFile(
            pathFormat: "log-{Date}.txt",
            outputTemplate: "{Timestamp:HH:mm:ss} [{Level}] {SourceContext} Method:{MethodName} {Message:l}{Exception:l}\r\n");
```

**Comment by arteny** [comment]
Thanks

**Comment by arteny** [comment]
But what about .WriteTo.ColoredConsole? 
It doesn't work for this.

**Comment by SimonCropp** [comment]
Does it work without anotar

**Comment by SimonCropp** [comment]
can u upload a repro somewhere?

**Comment by SimonCropp** [comment]
repro please :)

**Comment by arteny** [comment]
Trying now and it works with ColoredConsole.
