### ISSUE TITLE
Serilog How to add Context in method where logging is done

### ISSUE THREAD

**Issue by vradzius** [Fody/Anotar#70]
Hi,

I want to dynamically add some data to logs using ForContext when I get it from callers

Sample maybe like this:
```
LogTo.Debug("First Log");
Log.Logger = Log.ForContext("Parameter1", Data);
LogTo.Debug("Second Log");
Log.Logger = Log.ForContext("Parameter2", Data);
LogTo.Debug("Third Log");
```
Those two context Parameters never get logged.
I want to add them globally to all log methods but I did not know them at construction time I only get them after some method call.

Could you propose some solution for this?

Thank you.

**Comment by SimonCropp** [comment]
can u upload a repo somewhere that illustrates your problem

**Comment by SimonCropp** [comment]
let me know if u ever manage that repro

**Comment by vaidotasradzius** [comment]
Does this sample posted sample not enough:
`class LogTesting {`
`  public void TestLogging()`
`  {`
`    LogTo.Debug("First Log");`
`    Log.Logger = Log.ForContext("Parameter1", "Value1");`
`    LogTo.Debug("Second Log");`
`    Log.Logger = Log.ForContext("Parameter2", "Value2");`
`    LogTo.Debug("Third Log");`
`  }`
`}`

And if you look in the log.
You wont get Parameter1 and Parameter2 in logs, for second and third line.
