### ISSUE TITLE
Cannot compile on .Net 3.5 (NLog)

### ISSUE THREAD

**Issue by Nikey646** [Fody/Anotar#71]
Due to the Reference assembly being compiled as a Portable project, it's not possible to compile a .Net 3.5 project, and results in an Error generated during the MSBuild phase.

Error Output:

    1>MSBUILD : error : Fody: An unhandled exception occurred:
    1>MSBUILD : error : Exception:
    1>MSBUILD : error : Sequence contains no matching element
    1>MSBUILD : error : StackTrace:
    1>MSBUILD : error :    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
    1>MSBUILD : error :    at ModuleWeaver.LoadSystemTypes() in C:\projects\anotar\Common\SystemTypesResolver.cs:line 24
    1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\anotar\NLogFody\ModuleWeaver.cs:line 29
    1>MSBUILD : error :    at lambda_method(Closure , Object )
    1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 164
    1>MSBUILD : error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 82
    1>MSBUILD : error : Source:
    1>MSBUILD : error : System.Core
    1>MSBUILD : error : TargetSite:
    1>MSBUILD : error : TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
    1>MSBUILD : error : 

Changing the my project Target Framework to 4.0 prevents the error from occurring, however i need to target 3.5, and upgrading to 4.0 is not an option.

**Comment by SimonCropp** [comment]
@Nikey646 i must admit i am conflicted about this one. 3.5 is over 8 years old. is it fair to expect new tools/libs released in 2016 to support systems that cant update to 4.0?

**Comment by Nikey646** [comment]
When you consider that Unity runs a version of Mono for .Net 3.5, and still has developers actively creating new games for all 3 major platforms (And even potentially Mobile Devices), It kind of changes the situation, since it goes from an 8 year old Version, to an 8 year old version that is driving the arguably best Game Engine for the .Net framework.

In all honesty, if you decide not to support .Net 3.5, i can completely understand your decision, and I'll just have to resort to manually implementing a logger, and losing that handy Method/Line information ;(

**Comment by SimonCropp** [comment]
so where can i see doco/conversation about why unity has not updated and the future plan?

**Comment by Nikey646** [comment]
I don't have anything like a straight statement to give you, or anything as to why they haven't updated, but as for future plans (although be it old, it does appear to be relevant), [this](http://blogs.unity3d.com/2014/05/20/the-future-of-scripting-in-unity/) blog post briefly touches on plans for upgrading to a newer version of .Net (Unspecified) after the completion of their IL2CPP tool/lib, which is currently in development.

As for why they haven't updated, i can only speculate, but it's most likely due to the sheer amount of platforms they support, which presumably required heavy modifications to the Mono runtime, meaning upgrading isn't as simple as switching a few files with another.

**Comment by SimonCropp** [comment]
sorry but i dont want to get into the space of supporting an testing such old versions.

i appreciate the position this put you and am sorry.

**Comment by Nikey646** [comment]
No problem, if that is your choice that is perfectly fine.
