### ISSUE TITLE
anotar.splat.fody 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).

### ISSUE THREAD

**Issue by ghuntley** [Fody/Anotar#74]
:wave:
# Problem

> Install-Package anotar.splat.fody 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
> At line:1 char:1
> - install-package anotar.splat.fody
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>   - FullyQualifiedErrorId : 
>     NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
# Repro

File -> New UWP Library -> Install-Package

**Comment by SimonCropp** [comment]
current version supports netstandard1.1  which should support uwp
