### ISSUE TITLE
Allow custom message format

### ISSUE THREAD

**Issue by j2jensen** [Fody/Anotar#78]
It's really cool that Anotar gives us the opportunity to capture things like the method name and line number, but I don't always want that information output exactly the way that Anotar does it. It would be nice if we could customize the weaver to show this information in whatever way we want. You could also collect more information about the code, like the filename, and allow users to include this data in their format.

For example:
```
  <Anotar.Log4Net format="{methodName}: {message}" />
```
might yield:
```
    ConfigureLogging: Logging configured.
```
Whereas:
```
  <Anotar.Log4Net format="{fullFilePath}({line}): {fullClassPath}.{methodName}({methodArguments}):  {message}" />
```
Would produce:
```
    C:\Source\...\Startup.cs(10): ConfigureLogging(): Logging configured.
```

**Comment by SimonCropp** [comment]
sounds good. want to send a PR?

**Comment by SimonCropp** [comment]
let me know when u get to that PR
