### ISSUE TITLE
How to install MetroLog Anotar to UWP apps?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Fody/Anotar#79]
Steps
1. Cloned this project https://github.com/Fody/UniversalAppSample/
2. Installed Metrolog using nuget
3. Tried install Anotar.Metrolog.Fody using nuget package manager, get Severity Code    Description Project File    Line    Suppression State
Error       Package restore failed. Rolling back package changes for 'AppWithFody'.         0   
1. Tried install Anotar.CommonLogging.Fody using nuget package manager, get Severity    Code    Description Project File    Line    Suppression State
   Error       Package restore failed. Rolling back package changes for 'AppWithFody'.         0   
2. Tried install Anotar.LibLog.Fody using nuget package manager, get Severity   Code    Description Project File    Line    Suppression State
   Error       Package restore failed. Rolling back package changes for 'AppWithFody'.         0   

Other warning that i get are 
Severity    Code    Description Project File    Line    Suppression State
Warning     Invalid search path 'C:\Visual8\VC\LIB' specified in 'LIB environment variable' -- 'directory does not exist'   AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Certificate file 'AppWithFody_TemporaryKey.pfx' not found.  AppWithFody  
Warning     Invalid search path 'C:\Visual8\SDK\v2.0\lib' specified in 'LIB environment variable' -- 'directory does not exist' AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Invalid search path 'C:\Visual8\SDK\v2.0\lib' specified in 'LIB environment variable' -- 'directory does not exist' AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Invalid search path 'C:\Visual8\VC\ATLMFC\LIB' specified in 'LIB environment variable' -- 'directory does not exist'    AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Invalid search path 'C:\Visual8\VC\ATLMFC\LIB' specified in 'LIB environment variable' -- 'directory does not exist'    AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Invalid search path 'C:\Visual8\VC\LIB' specified in 'LIB environment variable' -- 'directory does not exist'   AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Invalid search path 'C:\Visual8\VC\PlatformSDK\lib' specified in 'LIB environment variable' -- 'directory does not exist'   AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     Invalid search path 'C:\Visual8\VC\PlatformSDK\lib' specified in 'LIB environment variable' -- 'directory does not exist'   AppWithFody C:\iJam\Project\UWP\AnotarUWP\AppWithFody\CSC  
Warning     The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.   AppWithFody         

How do i install anotar to use with metrolog and uwp?

**Comment by SimonCropp** [comment]
given metro log is essentially abandoned this will not be fixed
