### ISSUE TITLE
Allow `IFormatProvider` to be customized or provided to formatting log methods.

### ISSUE THREAD

**Issue by j2jensen** [Fody/Anotar#80]
Microsoft's Code Analysis Rules will yield a warning or error when strings are formatted without an explicit `IFormatProvider`, because there are situations where you wouldn't want the resulting string to vary based on the current culture.

For code bases where Code Analysis Rules are set to make this an error, this makes the formatting `LogTo.*()` methods unusable, because there's no way to provide a format provider to the code that gets generated. Using a lambda function and manually formatting appears to not be an option, either--I'm guessing that the lambda's result gets thrown into a Formatting method in the emitted code?

It would be nice if we could configure the emitted code to use an `IFormatProvider`. Something like this:

```
  <Anotar.Log4Net FormatProvider="Invariant"/>
```

So that this:

```
LogTo.Debug("Item {0} not found", itemId);
```

would produce this:

```
logger.Debug(CultureInfo.InvariantCulture, "Method: 'Void MyMethod()'. Line: ~12. Item {0} not found", itemId);
```

**Comment by SimonCropp** [comment]
can u give me a failing unit test that illustrates this problem

**Comment by j2jensen** [comment]
No, because this is a build-time issue, not a run-time one. However, I have created a project at https://github.com/j2jensen/AnotarIssue80 that reproduces it.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
