### ISSUE TITLE
[Feature Request] conditionally remove logging

### ISSUE THREAD

**Issue by dracool** [Fody/Anotar#84]
Hey,
would be nice to support removing the logging from the assembly entirely (possibly with removal of the logging framework reference). Logging is very helpful in libraries to debug them, but polluting the release Assembly by forcing a specific logging framework on those using it would not be nice.

I know this can be done simply by wrapping each usage of logging in a `#if DEBUG .... #endif` but that is a very cumbersome solution and seeing as this is designed to simplify logging that might be a good idea.

**Comment by michael-freidgeim-webjet** [comment]
I strongly disagree with "Logging is very helpful in libraries to debug them, but polluting the release".
The whole purpose of logging is to get information in production, when you can't debug. However your logging library should support configuration, that allow you to log different type of information- fatal,err,warn,inf,trace, verbose. Normally in production you set level to Warn, but can be switch to trace to investigate issue.

**Comment by dracool** [comment]
I think the point of this was misunderstood.
The point is NOT to remove logging from production programs, that is obviously a bad idea. The point was to allow logging in an open source LIBRARY debug build, without forcing everyone who installs it to add a specific logging framework (version) dependency. This is especially a problem for pre-compiled installs from e.g. NuGet.

This mainly originates from the frustration of having multiple different logging framework dependencies (on multiple versions, even) through different libraries used in a project, without any need for them.

**Comment by SimonCropp** [comment]
Sorry but given the nature of how anotar is designed to work this is not really within its problem domain
