### ISSUE TITLE
dotCover missing async methods containing LogTo

### ISSUE THREAD

**Issue by dsarfati** [Fody/Anotar#86]
Our team just started using Anotar and I'm noticing very odd behavior with dotCover when using LogTo statements. When we LogTo in our async method, the method no longer shows up in the dotCover coverage tree. When we make the method non async or comment out the LogTo it works fine. Here are some examples:

```c#
public Task TestLog()
{
    LogTo.Info("Test Log");

    return Task.CompletedTask;
}

public async Task TestAsync()
{
    await Task.Delay(1);
}

//This is the one that is missing!!!
public async Task TestAsyncLog()
{
    LogTo.Info("Test Log Async");
   
    await Task.Delay(1);
}
```
Not sure if it matters, but we are using NLog and when we tried it with the non-Anotar way of using NLog everything works fine.

**Comment by SimonCropp** [comment]
Closing since this is fixed on the dot cover side
