### ISSUE TITLE
LogToErrorOnExceptionAttribute + Common.Logging = ArgumentNullException

### ISSUE THREAD

**Issue by smartcaveman** [Fody/Anotar#88]
`LogToErrorOnExceptionAttribute` does not work correctly with Common.Logging.  Instead of logging the exception and then rethrowing the original error, it fails to log the exception and throws its own `ArgumentNullException`.  

I dug in, and here's why:

- the code generated by Anotar looks like:

		void repro(object arg)
		{
			try
			{
				throw new Exception("Anotar + Common.Logging is broken.");
			}
			catch (Exception exception)
			{
				string format = string.Format("Exception occurred in 'Void repro(obj arg)'.  arg '{0}'", new object[]
				{
					arg
				});
				if (ToolViewModel.AnotarLogger.IsErrorEnabled)
				{
					ContainingType.AnotarLogger.ErrorFormat(format, exception, null);
				}
				throw;
			}
		}

- The problem is in the line `ContainingType.AnotarLogger.ErrorFormat(format, exception, null);` passing null to the third argument, because:
   - [Common.Logging eventually passes this null into the array argument of `String.Format`](https://github.com/net-commons/common-logging/blob/526347b9260d66059f90c1b06d04cdd75cdba3df/src/Common.Logging.Portable/Logging/Factory/AbstractLogger.cs#L164)

- This is a problem because it violates the `String.Format` contract, e.g.:
  - `string.Format(CultureInfo.CurrentCulture, "I throw no errors.", new object[0])`
  - `string.Format(CultureInfo.CurrentCulture, "But I do!", null)`

**Comment by SimonCropp** [comment]
can u upload a solution that reproduce this issue?
