### ISSUE TITLE
Support for .NET Standard

### ISSUE THREAD

**Issue by ravensorb** [Fody/Anotar#91]
Any plans for support .NET Standard Projects

**Comment by hizzz** [comment]
Would be great to have this one!

**Comment by tpluscode** [comment]
Which loggers do you guys use?

**Comment by mstyura** [comment]
@tpluscode we use `Anotar.Custom.Fody` nuget package.

**Comment by tpluscode** [comment]
@mstyura you're in luck, `Anotar.Custom` comes first. I shall be merging #92 soon and I'll publish a pre-release to NuGet.

**Comment by tpluscode** [comment]
Okay, please try [`3.3.1-beta0001`](https://www.nuget.org/packages/Anotar.Custom.Fody/3.3.1-beta0001)

**Comment by tpluscode** [comment]
Please track these issues for support of specific loggers:

#95 - Catel
#96 - CommonLogging
#97 - LibLog
#98 - Log4Net
#99 - MetroLog
#94 - NLog
#100 - NServiceBus
#101 - Serilog
#102 - Splat
