### ISSUE TITLE
The weaver assembly 'Anotar.Splat.Fody' references an out of date version of Mono.Cecil.dll problem after updating Xamarin

### ISSUE THREAD

**Issue by xplatsolutions** [Fody/Anotar#93]
I have issues after updating Xamarin Studio. I use Fody, Anotar.Splat.Fody, ReactiveUI.Fody. I have updated Fody and ReactiveUI.Fody but unable to update Anotar.Splat.Fody due to Splat constraints and ReactiveUI. Any ideas regarding the below message?

> Error: Fody: The weaver assembly 'Anotar.Splat.Fody, Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' references an out of date version of Mono.Cecil.dll (cecilReference.Version). At least version 0.10 is expected. The weaver needs to add a NuGet reference to FodyCecil version 2.0.

**Comment by mstyura** [comment]
Looks like nuspec file need to be updated. Similar issue were in other fody plugin https://github.com/realm/realm-dotnet/issues/1364 and was fixed by adding `FodyCecil` to `nuspec` file https://github.com/Fody/Costura/pull/187/files /cc @tpluscode

**Comment by SimonCropp** [comment]
Cecil should  not be in the nuspec. I will look into why it was incorrectly included in costua

**Comment by SimonCropp** [comment]
Ok. That was not merged in costura

**Comment by SimonCropp** [comment]
@xplatsolutions this should be fixed in new nuget

**Comment by xplatsolutions** [comment]
@SimonCropp thank you, I appreciate it, this will solve the issue for me to update Xamarin latest mono I believe.

**Comment by tpluscode** [comment]
@SimonCropp so what is the issue actually?

**Comment by xplatsolutions** [comment]
OK, I'm actually back to this since I have a restriction updating Anotar.Splat.Fody due to a limitation in reactiveui-core requiring Splat <2.0.0 and Anotar.Splat.Fody requiring =>2.0.0. Pretty much Splat is killing me right now. Any suggestions?

**Comment by xplatsolutions** [comment]
Removed Anotar.Splat.Fody for now...

**Comment by SimonCropp** [comment]
@tpluscode i think it was this fix https://github.com/Fody/Anotar/commit/09f3cde5ca2d8049000fa6c7244fdc91242d7411#diff-f929876324c6a3a41aa1e8e8b0d1542d

@xplatsolutions 

> OK, I'm actually back to this since I have a restriction updating Anotar.Splat.Fody due to a limitation in reactiveui-core requiring Splat <2.0.0 and Anotar.Splat.Fody requiring =>2.0.0. Pretty much Splat is killing me right now.

I think u need to push (ask nucely) reactiveui-core to update to a newer version of splat. 2.0 of splat has been out since Nov 2016 so it is a reasonable request. cc @paulcbetts
